<?php include("header.php"); ?>
        <section class="privacy-policy-area">
            <div class="container">
                <div class="row row--30">
                    <div class="col-lg-12">
                        <div class="privacy-policy">
                            <div class="text-block">
                                <h3 class="title" style="font-size:23px">Effective: January 1st, 2022</h3>
                                <p align="justify">
This Privacy Policy outlines the policies and procedures of Mentoria Overseas Education regarding the collection, use, and disclosure of your information. By continuing to use our Services, you consent to the terms outlined in this policy.<br><br>
If you have any queries or concerns about this Privacy Policy, please reach out to us at support@mentoriaoverseas.com<br><br>
                                
                               
                                <b>Information Collected Upon Registration:</b><br>
When you register on Mentoria Overseas Education, using platforms like Facebook, you grant us limited access to your personal information such as your name, photo, and email address. Certain information, such as your name and photo, may be publicly visible on our Services, including your profile page and search results.<br><br>

<b>Additional Information:</b><br>
You have the option to provide additional information like your academic background and preferences for international schools. This data helps us assist you in finding suitable schools and connecting with relevant individuals. Providing additional information is voluntary.<br><br>

<b>Schools, Programs, and Other Public Information:</b><br>
Our Services are designed to help you connect with universities of interest. When you select a university, we share your profile information along with the programs you are interested in and the information you are seeking. We do not disclose to universities which other institutions you are interested in.<br><br>

<b>Log Data:</b><br>
We automatically record information ("Log Data") generated by your use of the Services. Log Data may include your IP address, browser type, referring domain, pages visited, and search terms. We retain Log Data for a period of 18 months, after which we either delete it or remove common identifiers like usernames, IP addresses, or email addresses.<br><br>

<b>Links:</b><br>
We may track your interactions with links on Mentoria Overseas to improve our Services and share aggregate click statistics, such as the number of clicks on a specific link.<br><br>

<b>Information Sharing and Disclosure</b><br><br>

<b>Your Consent:</b><br>
We may share or disclose your information with the universities you've selected. We might also share your information with our partners, who may follow up with you regarding your interest in studying abroad.<br><br>

<b>Law and Harm:</b><br>
We may preserve or disclose your information if we believe it is reasonably necessary to comply with a law, regulation, legal request, protect someone's safety, address fraud, security, or technical issues, or safeguard Mentoria Overseas' rights or property.<br><br>

<b>Business Transfers:</b><br>
If Mentoria Overseas Education is involved in a merger, acquisition, bankruptcy, reorganization, or asset sale, your information may be transferred or sold as part of that transaction. The terms of this privacy policy will apply to your information as transferred to the new entity.<br><br>

<b>Non-Private or Non-Personal Information:</b><br>
We may share or disclose your non-private, aggregated, or non-personal information, such as public posts or the number of users who clicked on a particular link.<br><br>

<b>Protection of Your Data</b><br><br>

<b>Data Security:</b><br>
Mentoria Overseas Education employs robust security measures to protect your data from unauthorized access, alteration, disclosure, or destruction. We use industry-standard encryption protocols and secure socket layer (SSL) technology to safeguard your information during transmission.<br><br>

<b>Access Control:</b><br>
Access to your personal data is limited to authorized Mentoria Overseas Education employees, partners, and service providers who need to process this information. All individuals with access are bound by strict confidentiality obligations and may face disciplinary action or legal consequences if they fail to meet these obligations.<br><br>

<b>Data Integrity:</b><br>
We take reasonable steps to ensure that the personal information we collect is accurate, complete, and up-to-date. We encourage you to review and update your information regularly. If you believe that any data we hold about you is inaccurate or incomplete, please contact us promptly, and we will correct or update it as necessary.<br><br>

<b>Account Security:</b><br>
It's important to keep your Mentoria Overseas Education account credentials confidential and secure. Please do not share your password or any other account-related information with others. If you suspect unauthorized access to your account or any security breach, notify us immediately at support@mentoriaoverseas.com.<br><br>

<b>Incident Response:</b><br>
In the event of a data breach or unauthorized access to your information, Mentoria Overseas Education has an incident response plan in place. We will promptly investigate the incident, take necessary remedial actions, and inform affected users as required by applicable laws and regulations.<br><br>

<b>Children's Privacy:</b><br>
Mentoria Overseas Education does not knowingly collect personal information from children under the age of 13. If we learn that we have inadvertently collected personal data from a child under 13 years old, we will take immediate steps to delete that information. If you believe we might have any information from or about a child under 13, please contact us at support@mentoriaoverseas.com.<br><br>

<b>International Data Transfers:</b><br>
If you are accessing Mentoria Overseas Education services from outside India, please be aware that your data may be transferred to and stored on servers located in India or other countries. By using our Services, you consent to the transfer of your data to these locations, which may have different data protection laws than your home country.<br><br>

<b>Questions and Concerns:</b><br>
If you have any questions, concerns, or complaints about the protection of your data, please contact us at support@mentoriaoverseas.com. We take all privacy-related inquiries seriously and will respond promptly to address your concerns. Your privacy and the security of your data are of utmost importance to us at Mentoria Overseas Education.
                                </p>
                            </div>
                            
                            
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>
        <?php include("footer.php"); ?>